### ISSUE TITLE
unresolved dependency: com.concurrentthought.cla#command-line-arguments_2.10;0.4.0: not found

### ISSUE THREAD

**Issue by intracer** [deanwampler/command-line-arguments#2]
Cannot compile the project, it seems to need it's own output artifacts?
$ sbt compile
[info] Loading global plugins from /home/ilya/.sbt/0.13/plugins
[info] Updating {file:/home/ilya/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /home/ilya/wm/command-line-arguments/project
[info] Updating {file:/home/ilya/wm/command-line-arguments/project/}command-line-arguments-build...
[info] Resolving org.scala-lang#scalap;2.10.5 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.sbt:sbt-git:0.6.4 -> 0.8.4
[warn] Run 'evicted' to see detailed eviction warnings
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to command-line-arguments (in build file:/home/ilya/wm/command-line-arguments/)
[warn] Credentials file /home/ilya/.ivy2/.credentials does not exist
[info] Updating {file:/home/ilya/wm/command-line-arguments/}core...
[info] Resolving org.scala-lang#scalap;2.11.8 ...
[info] Done updating.
[warn] Credentials file /home/ilya/.ivy2/.credentials does not exist
[info] Updating {file:/home/ilya/wm/command-line-arguments/}examples...
[info] Resolving com.concurrentthought.cla#command-line-arguments_2.11;0.4.0 ...
[info] Compiling 5 Scala sources to /home/ilya/wm/command-line-arguments/core/target/scala-2.11/classes...
[info] Resolving org.scala-lang#scalap;2.11.8 ...
[info] Done updating.
[info] Updating {file:/home/ilya/wm/command-line-arguments/}dist...
[info] 'compiler-interface' not yet compiled for Scala 2.11.8. Compiling...
[info] Updating {file:/home/ilya/wm/command-line-arguments/}root...
[info] Resolving com.concurrentthought.cla#command-line-arguments_2.10;0.4.0 ...
[warn]  module not found: com.concurrentthought.cla#command-line-arguments_2.10;0.4.0
[warn] ==== local: tried
[warn]   /home/ilya/.ivy2/local/com.concurrentthought.cla/command-line-arguments_2.10/0.4.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/concurrentthought/cla/command-line-arguments_2.10/0.4.0/command-line-arguments_2.10-0.4.0.pom
[warn] ==== preloaded-local: tried
[warn]   /home/ilya/wm/command-line-arguments/dist/target/preloaded-local-temp/com.concurrentthought.cla/command-line-arguments_2.10/0.4.0/ivys/ivy.xml
[info] Resolving com.concurrentthought.cla#command-line-arguments-examples_2.10;0.4.0 ...
[warn]  module not found: com.concurrentthought.cla#command-line-arguments-examples_2.10;0.4.0
[warn] ==== local: tried
[warn]   /home/ilya/.ivy2/local/com.concurrentthought.cla/command-line-arguments-examples_2.10/0.4.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/concurrentthought/cla/command-line-arguments-examples_2.10/0.4.0/command-line-arguments-examples_2.10-0.4.0.pom
[warn] ==== preloaded-local: tried
[warn]   /home/ilya/wm/command-line-arguments/dist/target/preloaded-local-temp/com.concurrentthought.cla/command-line-arguments-examples_2.10/0.4.0/ivys/ivy.xml
[info] Resolving org.scala-lang#scalap;2.10.5 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.concurrentthought.cla#command-line-arguments_2.10;0.4.0: not found
[warn]  :: com.concurrentthought.cla#command-line-arguments-examples_2.10;0.4.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.scala-lang#scala-library;2.11.8 ...
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.concurrentthought.cla:command-line-arguments_2.10:0.4.0 ()
[warn]            +- dist:dist_2.10:0.1-SNAPSHOT
[warn]          com.concurrentthought.cla:command-line-arguments-examples_2.10:0.4.0 ()
[warn]            +- dist:dist_2.10:0.1-SNAPSHOT
[info] Resolving org.scala-lang#scalap;2.11.8 ...
[info] Done updating.
[info]   Compilation completed in 18.887 s
[info] Compiling 1 Scala source to /home/ilya/wm/command-line-arguments/examples/target/scala-2.11/classes...
sbt.ResolveException: unresolved dependency: com.concurrentthought.cla#command-line-arguments_2.10;0.4.0: not found
unresolved dependency: com.concurrentthought.cla#command-line-arguments-examples_2.10;0.4.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (dist/*:update) sbt.ResolveException: unresolved dependency: com.concurrentthought.cla#command-line-arguments_2.10;0.4.0: not found
[error] unresolved dependency: com.concurrentthought.cla#command-line-arguments-examples_2.10;0.4.0: not found
[error] Total time: 34 s, completed Dec 16, 2016 10:46:43 PM

**Comment by deanwampler** [comment]
Thanks for letting me know. I had to clean up some "broken windows" in my build's publishing process. I think it's fixed now, but it will take a few hours for the 0.4.0 artifacts to appear on the Maven servers. If you're in a hurry, you can clone this repo, run `publishLocal`, and you'll have local copies in `$HOME/.ivy2/local`.

**Comment by deanwampler** [comment]
Both 2.10 and 2.11 builds for v0.4.0 are now available. Sorry for the trouble.
